#!/usr/bin/env python3
"""
build-data-index.py — 扫消费仓 apps/<svc>/migrations/*.sql，
生成 docs/services/<svc>/_data-index.md（ROLE=AUTO）。

用法：
  python3 scripts/build-data-index.py             # 全量重写
  python3 scripts/build-data-index.py --check     # 漂移检测，diff 非空即 exit 1（CI）
  python3 scripts/build-data-index.py --service svc-01-trading-api
  python3 scripts/build-data-index.py --target /path/to/consumer-repo

设计：
- 输入：apps/<svc>/migrations/*.sql（命名约定 NNNN_verb_noun.sql）
- 输出：docs/services/<svc>/_data-index.md（VIEW；首行 ROLE=AUTO，禁手改）
- 解析：正则提取 CREATE TABLE / CREATE INDEX / ALTER TABLE ADD COLUMN
- 不做 SQL 语法树解析（够用即可；服务自己用 sqlx/atlas 兜底）

退出码：
  0 = 一致 / 写入成功
  1 = 漂移（--check 模式下）
  2 = 参数 / 路径错误
"""
from __future__ import annotations

import argparse
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

# ---------- 解析器（足够轻量；不追求 SQL 全语法覆盖） ----------

RE_CREATE_TABLE = re.compile(
    r"CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?[\"`]?(\w+)[\"`]?\s*\((.*?)\);",
    re.IGNORECASE | re.DOTALL,
)
RE_CREATE_INDEX = re.compile(
    r"CREATE\s+(UNIQUE\s+)?INDEX\s+(?:IF\s+NOT\s+EXISTS\s+)?[\"`]?(\w+)[\"`]?\s+ON\s+[\"`]?(\w+)[\"`]?\s*\(([^)]+)\)",
    re.IGNORECASE,
)
RE_ALTER_ADD = re.compile(
    r"ALTER\s+TABLE\s+[\"`]?(\w+)[\"`]?\s+ADD\s+(?:COLUMN\s+)?[\"`]?(\w+)[\"`]?\s+(\w+)",
    re.IGNORECASE,
)


def parse_columns(body: str) -> list[str]:
    """从 CREATE TABLE body 抽列名（忽略 CONSTRAINT/PRIMARY KEY/INDEX/FOREIGN 等）。"""
    cols = []
    depth = 0
    buf = ""
    for ch in body:
        if ch == "(":
            depth += 1
            buf += ch
        elif ch == ")":
            depth -= 1
            buf += ch
        elif ch == "," and depth == 0:
            cols.append(buf.strip())
            buf = ""
        else:
            buf += ch
    if buf.strip():
        cols.append(buf.strip())
    out = []
    for c in cols:
        head = c.split()[0].strip("\"`").upper()
        if head in {"CONSTRAINT", "PRIMARY", "UNIQUE", "FOREIGN", "CHECK", "INDEX", "KEY"}:
            continue
        out.append(c.split()[0].strip("\"`"))
    return out


def scan_service(migrations_dir: Path) -> dict:
    """返回 {tables, indexes, files, last_mtime}."""
    tables: dict[str, dict] = {}  # name → {cols:set, source:str}
    indexes: list[dict] = []
    files = sorted(migrations_dir.glob("*.sql"))
    for f in files:
        sql = f.read_text(encoding="utf-8")
        for m in RE_CREATE_TABLE.finditer(sql):
            name, body = m.group(1), m.group(2)
            tables.setdefault(name, {"cols": [], "source": f.name})
            tables[name]["cols"] = parse_columns(body)
        for m in RE_ALTER_ADD.finditer(sql):
            tbl, col = m.group(1), m.group(2)
            t = tables.setdefault(tbl, {"cols": [], "source": f.name})
            if col not in t["cols"]:
                t["cols"].append(col)
        for m in RE_CREATE_INDEX.finditer(sql):
            uniq, idx, tbl, cols = m.group(1), m.group(2), m.group(3), m.group(4)
            indexes.append({
                "name": idx,
                "table": tbl,
                "cols": [c.strip().strip('"`') for c in cols.split(",")],
                "unique": bool(uniq),
                "source": f.name,
            })
    return {"tables": tables, "indexes": indexes, "files": [f.name for f in files]}


# ---------- 渲染 ----------

HEADER = """<!-- ROLE: AUTO | machine-generated by scripts/build-data-index.py, DO NOT EDIT -->
<!-- AUTO-GENERATED, DO NOT EDIT — 由 scripts/build-data-index.py 扫 apps/{svc}/migrations/*.sql 生成 -->
# `{svc}` · Data Index

> **生成时间（UTC）**：{ts}
> **迁移文件数**：{nfiles}
> **来源**：`apps/{svc}/migrations/*.sql`（L3 SSOT）
> 治理细则见 [`docs/architecture/00_governance.md §1`](../../architecture/00_governance.md)。
"""


def render(svc: str, data: dict) -> str:
    out = [HEADER.format(svc=svc, ts=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"), nfiles=len(data["files"]))]
    out.append("\n## 1. 表清单\n")
    if not data["tables"]:
        out.append("_（无）_\n")
    else:
        out.append("| 表名 | 字段数 | 字段 | 来源迁移 |\n")
        out.append("|---|---:|---|---|\n")
        for name in sorted(data["tables"]):
            t = data["tables"][name]
            cols = ", ".join(f"`{c}`" for c in t["cols"]) or "_(无)_"
            out.append(f"| `{name}` | {len(t['cols'])} | {cols} | `{t['source']}` |\n")
    out.append("\n## 2. 索引清单\n")
    if not data["indexes"]:
        out.append("_（无）_\n")
    else:
        out.append("| 索引 | 表 | 字段 | UNIQUE | 来源迁移 |\n")
        out.append("|---|---|---|:-:|---|\n")
        for ix in sorted(data["indexes"], key=lambda x: (x["table"], x["name"])):
            cols = ", ".join(f"`{c}`" for c in ix["cols"])
            uniq = "✅" if ix["unique"] else "—"
            out.append(f"| `{ix['name']}` | `{ix['table']}` | {cols} | {uniq} | `{ix['source']}` |\n")
    out.append("\n## 3. 迁移文件\n")
    if not data["files"]:
        out.append("_（无）_\n")
    else:
        for f in data["files"]:
            out.append(f"- `{f}`\n")
    return "".join(out)


# ---------- 主流程 ----------

def discover_services(target: Path) -> list[tuple[str, Path]]:
    apps = target / "apps"
    if not apps.is_dir():
        return []
    out = []
    for svc_dir in sorted(apps.iterdir()):
        if not svc_dir.is_dir() or not svc_dir.name.startswith("svc-"):
            continue
        mig = svc_dir / "migrations"
        if mig.is_dir():
            out.append((svc_dir.name, mig))
    return out


def process(svc: str, mig: Path, target: Path, check: bool) -> int:
    data = scan_service(mig)
    if not data["files"]:
        return 0
    docs_dir = target / "docs" / "services" / svc
    docs_dir.mkdir(parents=True, exist_ok=True)
    dest = docs_dir / "_data-index.md"
    new = render(svc, data)
    if check:
        old = dest.read_text(encoding="utf-8") if dest.exists() else ""
        # 忽略时间戳行的差异（每次都会变）
        def strip_ts(s: str) -> str:
            return re.sub(r"\*\*生成时间（UTC）\*\*：[\d\- :A-Z]+", "**生成时间（UTC）**：<TS>", s)
        if strip_ts(old) != strip_ts(new):
            print(f"[drift] {dest}", file=sys.stderr)
            return 1
        return 0
    dest.write_text(new, encoding="utf-8")
    print(f"[write] {dest}")
    return 0


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--target", default=".", help="消费仓根目录（默认 cwd）")
    p.add_argument("--service", default=None, help="只处理指定 svc-XX-bctx-role")
    p.add_argument("--check", action="store_true", help="漂移检测，不写文件；diff 非空 exit 1")
    args = p.parse_args()

    target = Path(args.target).resolve()
    if not (target / "apps").is_dir():
        print(f"[error] {target}/apps/ 不存在；请在消费仓根目录运行或加 --target", file=sys.stderr)
        return 2

    svcs = discover_services(target)
    if args.service:
        svcs = [s for s in svcs if s[0] == args.service]
        if not svcs:
            print(f"[error] 未找到服务 {args.service}", file=sys.stderr)
            return 2

    rc = 0
    for svc, mig in svcs:
        rc |= process(svc, mig, target, args.check)
    return rc


if __name__ == "__main__":
    sys.exit(main())
